name: inftrain
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - cudatoolkit=9.2
  - cython
  - nose
  - numpy
  - openblas-devel
  - pip
  - psutil
  - pysoundfile
  - pytorch>=1.5.0
  - torchvision
  - torchaudio
  - tqdm
  - pip:
      - progressbar2
      - "git+https://github.com/MarvinLvn/CPC_torch.git"
      - "git+https://github.com/fairinternal/CPC_torch.git"
      - --editable=git+https://github.com/fairinternal/speech_augment.git@9f0564344740120f5b3687c24d5e009674d51aac#egg=augment