name: inftrain
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - cudatoolkit=9.2
  - cython
  - nose
  - numpy>=1.20
  - openblas-devel
  - pip
  - psutil
  - pysoundfile
  - pytorch>=1.5.0
  - torchvision
  - torchaudio
  - tqdm
  - click
  - pyyaml
  - scipy
  - joblib
  - pandas=1.2.4
  - pip:
      - progressbar2
      - sox
      - "git+https://github.com/bootphon/zerospeech2021.git"
